
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "converter.go",
        "types.go",
    ],
    importpath = "github.com/chrusty/protoc-gen-jsonschema/internal/converter",
    visibility = ["//visibility:public"],
    deps = [],
)
